#!/usr/bin/python3

import lnetatmo

authorization = lnetatmo.ClientAuth()
station_data = lnetatmo.WeatherStationData(authorization)

print ("Current temperature (inside/outside): %s / %s C, Wind: %s km/h" %
        ( station_data.lastData()['Indoor']['Temperature'],
          station_data.lastData()['Outdoor']['Temperature'],
          station_data.lastData()['Veranda']['GustStrength'])
      )

data = station_data.lastData(exclude=3600)
print(data.keys())
for module_name in data.keys():
    for variable in data[module_name]:
    	print('module %s: var %s' % (module_name, variable))
